import heapq

class Node:
    def __init__(self, position, time=0, parent=None):
        self.position = position
        self.time = time # NEW: Nodes must now track the time step
        self.parent = parent
        self.g = 0 # Distance from start node
        self.h = 0 # Distance to goal node
        self.f = 0 # Total cost

    def __eq__(self, other):
        # NEW: Two nodes are only equal if they share the same position AND time
        return self.position == other.position and self.time == other.time

    def __lt__(self, other):
        return self.f < other.f

def heuristic(a, b):
    """
    Calculates the Manhattan distance between two grid coordinates.
    Used as an admissible and consistent heuristic for A* orthogonal movement.
    """
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def astar(grid, start, end, constraints=None):
    """
    Space-Time A* Search Algorithm.
    Finds the optimal path from start to end while avoiding static obstacles
    and dynamic space-time constraints generated by the CBS high-level tree.
    
    Args:
        grid: 2D array representing the warehouse (0=free, 1=obstacle)
        start: Tuple (x, y) starting coordinate
        end: Tuple (x, y) goal coordinate
        constraints: List of tuples (location, timestep) to avoid
        
    Returns:
        List of (x, y) coordinates representing the optimal path, or None if unsolvable.
    """
    if constraints is None:
        constraints = []
        
    start_node = Node(start, time=0)
    end_node = Node(end)

    open_list = []
    closed_set = set() # Will now store (position, time) tuples

    heapq.heappush(open_list, start_node)

    while open_list:
        current_node = heapq.heappop(open_list)
        closed_set.add((current_node.position, current_node.time))

        # Found the goal
        if current_node.position == end_node.position:# NEW: Check if there are any future constraints at the goal AFTER our arrival time
            future_constraints = any(pos == end_node.position and t >= current_node.time for (pos, t) in constraints)
            if not future_constraints:
                path = []
                current = current_node
                while current is not None:
                    path.append(current.position)
                    current = current.parent
                return path[::-1] # Return reversed path

        # Generate children. NEW: Added (0,0) so the agent can WAIT in place
        directions = [(0, -1), (0, 1), (-1, 0), (1, 0), (0, 0)]
        
        for new_position in directions:
            node_position = (current_node.position[0] + new_position[0], current_node.position[1] + new_position[1])
            new_time = current_node.time + 1

            # Make sure within range
            if node_position[0] > (len(grid) - 1) or node_position[0] < 0 or node_position[1] > (len(grid[len(grid)-1]) -1) or node_position[1] < 0:
                continue

            # Make sure walkable terrain (0 is free space, 1 is obstacle/shelf)
            if grid[node_position[0]][node_position[1]] != 0:
                continue

            # NEW: Space-Time Constraint Check
            # If CBS tells us we cannot be at this position at this time, skip it
            if (node_position, new_time) in constraints:
                continue

            # Check if we have already evaluated this specific space-time state
            if (node_position, new_time) in closed_set:
                continue

            new_node = Node(node_position, time=new_time, parent=current_node)
            new_node.g = current_node.g + 1
            new_node.h = heuristic(new_node.position, end_node.position)
            new_node.f = new_node.g + new_node.h

            heapq.heappush(open_list, new_node)

    return None # No path found

def print_grid(grid, path, start, goal):
    grid_copy = [row[:] for row in grid]
    for step in path:
        if step != start and step != goal:
            grid_copy[step[0]][step[1]] = "*"
    
    grid_copy[start[0]][start[1]] = "S"
    grid_copy[goal[0]][goal[1]] = "G"

    print("\nWarehouse Grid Map:")
    for row in grid_copy:
        print(" ".join(str(cell) for cell in row))
    print(f"Path Length: {len(path) - 1} steps")

if __name__ == '__main__':
    # 0 = empty space, 1 = obstacle (warehouse shelf)
    warehouse_grid = [
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 1, 1, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 0, 1, 1, 1, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 1, 1, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 0, 1, 1, 1, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    ]

    start_pos = (0, 0) # Charging Station
    goal_pos = (4, 4)  # Pallet Location

    print("Running Baseline A* Search...")
    optimal_path = astar(warehouse_grid, start_pos, goal_pos)

    if optimal_path:
        print(f"Path found: {optimal_path}")
        print_grid(warehouse_grid, optimal_path, start_pos, goal_pos)
    else:
        print("No valid path exists.")